-- ============================================================
-- PhotoBuddy - Seed Data
-- Migration: 20240101000002_seed_data.sql
-- Static reference data that doesn't change with user activity
-- ============================================================

-- ============================================================
-- No static reference tables are needed for PhotoBuddy MVP.
-- The spec does not define lookup tables for categories, tags,
-- or other static content — those are generated by AI per photo.
--
-- User roles are defined as PostgreSQL enums in the schema.
-- Report categories are defined as PostgreSQL enums.
--
-- This migration is a placeholder in case seed data is needed
-- during development (e.g. a test admin user).
-- ============================================================

-- Example: Create an admin user record after signing up via Supabase Auth.
-- In production, promote users to admin via:
--   UPDATE public.users SET role = 'admin' WHERE username = 'your_admin_username';
--
-- This is intentionally NOT automated to prevent accidental admin creation.

SELECT 'Seed data migration complete - no static data required for PhotoBuddy MVP' AS note;
